#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>

typedef enum {
    RECORD_LAYOUT,
    RECORD_NODE
} RecordKind;

typedef struct {
    RecordKind kind;
    const char *family;
    const char *name;
    const char *payload;
    const char *cleanup;
} Record;

#define LAYOUT(family, name, declaration) {RECORD_LAYOUT, #family, #name, declaration, ""},
#define NODE(family, name, layout, cleanup) {RECORD_NODE, #family, #name, #layout, cleanup},

static const Record ast_records[] = {
#include "../src/ast_nodes.def"
};

static const Record hir_records[] = {
#include "../src/hir_nodes.def"
};

#undef NODE
#undef LAYOUT

typedef struct {
    const char *schema_path;
    const Record *records;
    size_t record_count;
} Schema;

typedef struct {
    const char *name;
    const char *enum_prefix;
    const char *root;
    const char *output_prefix;
} Family;

static const Family ast_families[] = {
    {"expr", "DS_EXPR_", "expr", "ast_expr"},
    {"stmt", "DS_STMT_", "stmt", "ast_stmt"},
};

static const Family hir_families[] = {
    {"expr", "DS_LOWER_EXPR_", "expr", "hir_expr"},
    {"stmt", "DS_LOWER_STMT_", "stmt", "hir_stmt"},
};

static void die(const char *message) {
    fprintf(stderr, "gen_nodes: %s\n", message);
    exit(1);
}

static void die_path(const char *message, const char *path) {
    fprintf(stderr, "gen_nodes: %s: %s\n", message, path);
    exit(1);
}

static int is_record(const Record *record, RecordKind kind, const char *family) {
    return record->kind == kind && strcmp(record->family, family) == 0;
}

static const Record *find_layout(const Schema *schema, const char *family, const char *name) {
    size_t i;
    for (i = 0; i < schema->record_count; i++) {
        const Record *record = &schema->records[i];
        if (is_record(record, RECORD_LAYOUT, family) && strcmp(record->name, name) == 0) return record;
    }
    return NULL;
}

static int layout_is_used(const Schema *schema, const char *family, const char *name) {
    size_t i;
    for (i = 0; i < schema->record_count; i++) {
        const Record *record = &schema->records[i];
        if (is_record(record, RECORD_NODE, family) && strcmp(record->payload, name) == 0) return 1;
    }
    return 0;
}

static void validate_family(const Schema *schema, const Family *family) {
    size_t i;
    for (i = 0; i < schema->record_count; i++) {
        const Record *record = &schema->records[i];
        size_t j;
        if (strcmp(record->family, family->name) != 0) continue;
        for (j = i + 1; j < schema->record_count; j++) {
            const Record *other = &schema->records[j];
            if (record->kind == other->kind && strcmp(other->family, family->name) == 0 && strcmp(record->name, other->name) == 0) {
                die(record->kind == RECORD_LAYOUT ? "duplicate layout name" : "duplicate node name");
            }
        }
        if (record->kind == RECORD_LAYOUT) {
            if (!layout_is_used(schema, family->name, record->name)) die("schema contains unused layout");
        } else if (strcmp(record->payload, "NONE") != 0 && !find_layout(schema, family->name, record->payload)) {
            die("node refers to unknown layout");
        }
    }
}

static void mkdir_if_needed(const char *path) {
    if (mkdir(path, 0777) != 0 && errno != EEXIST) die_path("cannot create output directory", path);
}

static FILE *open_output(const char *dir, const char *prefix, const char *suffix, char *path, size_t path_size) {
    FILE *file;
    if (snprintf(path, path_size, "%s/%s_%s.inc", dir, prefix, suffix) >= (int)path_size) die("output path too long");
    file = fopen(path, "w");
    if (!file) die_path("cannot open output", path);
    return file;
}

static void write_header(FILE *file, const Schema *schema) {
    fprintf(file, "/* Code generated by tools/gen_nodes.c from %s; DO NOT EDIT. */\n", schema->schema_path);
}

static void generate_kinds(const Schema *schema, const Family *family, const char *output_dir) {
    char path[1024];
    FILE *file = open_output(output_dir, family->output_prefix, "kinds", path, sizeof(path));
    size_t i;
    write_header(file, schema);
    for (i = 0; i < schema->record_count; i++) {
        const Record *record = &schema->records[i];
        if (is_record(record, RECORD_NODE, family->name)) fprintf(file, "    %s%s,\n", family->enum_prefix, record->name);
    }
    if (fclose(file) != 0) die_path("cannot write output", path);
}

static void generate_union(const Schema *schema, const Family *family, const char *output_dir) {
    char path[1024];
    FILE *file = open_output(output_dir, family->output_prefix, "union", path, sizeof(path));
    size_t i;
    write_header(file, schema);
    for (i = 0; i < schema->record_count; i++) {
        const Record *record = &schema->records[i];
        if (is_record(record, RECORD_LAYOUT, family->name)) fprintf(file, "        %s\n", record->payload);
    }
    if (fclose(file) != 0) die_path("cannot write output", path);
}

static void emit_cleanup(FILE *file, const char *root, const char *kind, const char *path) {
    if (strcmp(kind, "str") == 0) fprintf(file, "            free(%s->%s.data);\n", root, path);
    else if (strcmp(kind, "command") == 0) fprintf(file, "            ds_command_free(&%s->%s);\n", root, path);
    else if (strcmp(kind, "ast_expr") == 0) fprintf(file, "            ds_expr_free(%s->%s);\n", root, path);
    else if (strcmp(kind, "ast_stmt") == 0) fprintf(file, "            free_stmt(%s->%s);\n", root, path);
    else if (strcmp(kind, "ast_expr_vec") == 0) fprintf(file, "            free_expr_vec(&%s->%s);\n", root, path);
    else if (strcmp(kind, "ast_stmt_vec") == 0) fprintf(file, "            free_stmt_vec(&%s->%s);\n", root, path);
    else if (strcmp(kind, "ast_map_vec") == 0) fprintf(file, "            free_map_entry_vec(&%s->%s);\n", root, path);
    else if (strcmp(kind, "ast_fn_param_vec") == 0) fprintf(file, "            free_fn_param_vec(&%s->%s);\n", root, path);
    else if (strcmp(kind, "ast_case_arm_vec") == 0) fprintf(file, "            free_case_arm_vec(&%s->%s);\n", root, path);
    else if (strcmp(kind, "hir_expr") == 0) fprintf(file, "            lower_expr_free(%s->%s);\n", root, path);
    else if (strcmp(kind, "hir_stmt") == 0) fprintf(file, "            lower_stmt_free(%s->%s);\n", root, path);
    else if (strcmp(kind, "hir_expr_vec") == 0) fprintf(file, "            lower_expr_vec_free(&%s->%s);\n", root, path);
    else if (strcmp(kind, "hir_stmt_vec") == 0) fprintf(file, "            lower_stmt_vec_free(&%s->%s);\n", root, path);
    else if (strcmp(kind, "hir_map_vec") == 0) fprintf(file, "            lower_map_entry_vec_free(&%s->%s);\n", root, path);
    else if (strcmp(kind, "hir_case_arm_vec") == 0) fprintf(file, "            lower_case_arm_vec_free(&%s->%s);\n", root, path);
    else if (strcmp(kind, "row_schema") == 0) fprintf(file, "            row_schema_free(&%s->%s);\n", root, path);
    else die("unknown cleanup kind");
}

static void emit_cleanup_list(FILE *file, const char *root, const char *cleanup) {
    char buffer[1024];
    char *item;
    size_t n = strlen(cleanup);
    if (n >= sizeof(buffer)) die("cleanup list too long");
    memcpy(buffer, cleanup, n + 1);
    item = buffer;
    while (*item) {
        char *next = strchr(item, ',');
        char *colon;
        if (next) *next = '\0';
        colon = strchr(item, ':');
        if (!colon) die("cleanup entry requires kind:path");
        *colon = '\0';
        emit_cleanup(file, root, item, colon + 1);
        if (!next) break;
        item = next + 1;
    }
}

static void generate_free(const Schema *schema, const Family *family, const char *output_dir) {
    char path[1024];
    FILE *file = open_output(output_dir, family->output_prefix, "free", path, sizeof(path));
    size_t i;
    write_header(file, schema);
    for (i = 0; i < schema->record_count; i++) {
        const Record *record = &schema->records[i];
        if (!is_record(record, RECORD_NODE, family->name)) continue;
        fprintf(file, "        case %s%s:\n", family->enum_prefix, record->name);
        if (*record->cleanup) emit_cleanup_list(file, family->root, record->cleanup);
        fputs("            break;\n", file);
    }
    if (fclose(file) != 0) die_path("cannot write output", path);
}

static void generate_schema(const Schema *schema, const Family *families, size_t family_count, const char *output_dir) {
    size_t i;
    for (i = 0; i < family_count; i++) {
        validate_family(schema, &families[i]);
        generate_kinds(schema, &families[i], output_dir);
        generate_union(schema, &families[i], output_dir);
        generate_free(schema, &families[i], output_dir);
    }
}

int main(int argc, char **argv) {
    const char *output_dir = "src/generated";
    const Schema ast = {"src/ast_nodes.def", ast_records, sizeof(ast_records) / sizeof(ast_records[0])};
    const Schema hir = {"src/hir_nodes.def", hir_records, sizeof(hir_records) / sizeof(hir_records[0])};
    if (argc == 3 && strcmp(argv[1], "--output-dir") == 0) output_dir = argv[2];
    else if (argc != 1) die("usage: gen_nodes [--output-dir DIR]");
    mkdir_if_needed(output_dir);
    generate_schema(&ast, ast_families, sizeof(ast_families) / sizeof(ast_families[0]), output_dir);
    generate_schema(&hir, hir_families, sizeof(hir_families) / sizeof(hir_families[0]), output_dir);
    return 0;
}
